#!/bin/sh -e
exec 2>&1
exec /usr/bin/mysqld --basedir=/usr --datadir=/data/db/mysql/ --plugin-dir=/usr/lib/mysql/plugin --user=mysql --console --log-error=/data/log/mysql/mysql.err --pid-file=/var/run/mysqld/mysqld.pid --socket=/var/run/mysqld/mysqld.sock --port=3306
